version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5
    assignees:
      - "tkalus"
    labels:
      - "dependencies"
      - "go"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "go"
      include: "scope"
    groups:
      go-modules:
        patterns:
          - "*"
